/*----------------------------------------------------------------------------*/
/* Copyright (c) 2018 FIRST. All Rights Reserved.                             */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in the root directory of */
/* the project.                                                               */
/*----------------------------------------------------------------------------*/

package frc.robot;

import edu.wpi.first.wpilibj.RobotBase;

/**
 * Do NOT add any static variables to this class, or any initialization at all.
 * Unless you know what you are doing, do not modify this file except to
 * change the parameter class to the startRobot call.
 */
public final class Main {
  private Main() {
  }

  /**
   * Main initialization function. Do not perform any initialization here.
   *
   * <p>If you change your main robot class, change the parameter type.
   */
  public static void main(String... args) {
    RobotBase.startRobot(Robot::new);
  }
}

/*
jjjffffjffffjfffjjjji;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;iiiiiiiiiii;i;;;;;;,;,,;,,,;;;;;;;;;,,,,,;iiiiiiiiiiiiii
fffffffffffffffffjjj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,,,,,,,;;;;;;;iiiiiiiiiiiiiiiiiii;,,,,,;;iiiiiiiiiiiii
LLLLLLGLGLGGGGGGLGLj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii,,,,;;iiiiiiiiiiiiii
GGDDDDGGDGDGDGGGGGLj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii,,,,,;i;iiiiiiiiiiii
GDGGGGGGGGGGGGGGGGLj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;iiiiiiiiiiiiiiiii;iiiiiiiiiiiiiiiiii,,,,,;iiiii;iiiiiiii
GGGGGGGGGGGLGGGLGLLj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;iiiiiiiiiiiiiiiii,;iiiiiiiiiiiiiiiii,,,,,;i;iiiiiiiiiiii
GGGGLGGLGLLLLLLLLLLf;i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;iiiiiiiiiiiiiiii;,,iiiiiiiiiiiiiiiii,,,,,;iiiiiiiiiiiiii
GGLLLLGLLLGLLLLLLLfj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;iiiiiii;iiiiiiii;,,iiiiiiiiiiiiiiiii,,,,,;i;iii;iiiiiiii
LLLLLLLLLLLLLLLffffj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;iiiiiiiiiiiiiii;,,,,;iiiiiiiiiiiiiii,,,,,,iii;;i;iiiiiii
fLLLLfLffffffffffffj;;;;;;;;;;;;;;;;;;;,;;,;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,iiiiiiiiiiiiiii,,,,,;iiiiiiiiiiiiiii,,,,,,iiiii;iiiiiiii
fffffffffffjffjjjjjj;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii,,,,,,i;iii;;;;;;;;;
fffffffffjjjjjjjjjjj;;;;;,;;;;,,,;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii,,,,,,;;;;;;,;,,,,,,
jjjjjjjjjjjjjjjjjttt;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,iiiiiiiiiiiiiiiiiiiiiiii;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,
jjjjjjjjjtjjtttttttt;,,,,,,;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,ii;i;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
ttttttttttttttttttti,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
ttttttttttttttttitit,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
ttttttttttiitiiiiiii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
iittittiiiiiiiiiiiii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
tttititttiiiiiiiiiii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
iiiiiiiiiiiiiiiiiiii,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;
iiiiiiiiiiiiiiiiiiii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,iii
iiiiiiiiiiiiiiiiiiii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,iii
iiiiiiiiiiiiiiiiiiii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,iii
iiiiiiiiiiiiiiiiiiii;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,iti
iiiiiiiiiii;iiiiiiii;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,iti
iiiiiiiitiiiiiiiiiii;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;ii
iiiiiiiiiiiiiiiiiiii;,,,,,,,,,,,,,,,,,,,,,,,,:,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;ii
iiiiiiiiiiiiiiiiiiii;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;ii
iiiiiiiiiiiiiiiiiiii;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;ii
iiiiiiiiiiiiiiiiiiii;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;it
iiiiiiiiiiiiiiiiiiii;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,:,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
iiiiiiiiiiiiiiiiiiii;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
iiiiiiiiiiiiiiiiiiii;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,:,,,,,,,,,,,,,:,,,,,,,,,,:,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
iiiiiiiiiiiiiiiiiiiii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,:,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,:,,,,:,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
iiiiiiiiiiiiiiiiiiii;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,::,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
iiiiiiiiiiiiiiiiiiiii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,:,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,:,,,,:,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;
iiiiiiiiiiiiiiiiiiiii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,::,,,,,,,,,,:,,,,,,,,::,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;i;ii;i;;;;
iiiiiiiiiiiiiiiiiiiii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;i;;;i;iiii;;i
iiiiiiiiiiiiiiiiiiiii,,,,,,,,,,,,,,,,,,,,,,::,,,,,,,,,,,,,,:,,,,,,,,:,,,,,:,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;i;;ii;;;ii;ii;;i;iii;iii
iiiiiiiiiiiiiiiiiiiii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,::,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;i;;i;;;;;;;;;;;;;;i;;;;;;;;i;i;;;;iiiiii;ii;
iiiiiiiiiiiiiiiiiiiii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,:,,,,,,:,,,,,,,,,,,,,,,,,,,:,,,,,,:,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;;;;;;;i;i;i;iiiiii
iiiiiiii;iiiiiiiiiiii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,:,,,:,,,,:,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;;;;;;;;;;;;;;iiii;;i;;i;
iiiiiiiiiiiiiiiiiiiii,,,,,,,,,,,,,,,:,,,,,,:,,,:,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ii;i;i;i;i;;;iiiii;
iiiiiiiiiiiiiiiiii;ii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,:,,,,,,;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ii;;i;i;i;;i;i;i
iiiiiiiiiiiiiiiiiiiii,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;i;;;;;;;i;;;;;i;;i;;ii;iiii;
iiiiiiiiiiiiiiiiiiiii,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;;;;;i;;;;iiiiiiii
iiiiiiiiiiiiiiiiiiiii,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;;;;;;;;;;;;;ii;iii;;;iiiii;i;i
iiiiiiiiiiiiiiiiiiiii,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;i;;;i;;;;;;;;;;;;;;;;;i
iiiiiiiiiii;iiiiiiiii;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;;;;;;ii;;;i;;ii;;;i;;ii
iiiiiiiiiiiiiiiiiiiii;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;i;;;;;;;;;;;;i;i
iiiiiiiiiiiiiiiiiiiii;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ii;;;;;;;;;i;i;;;i;;iii;;;
iiiiiiiiiiiiiiii;iiii;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;;;;;;;;;;;;;;;;i;;;;;;i;iii;
iiiiiiiiiiiii;iiiiiii;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;ii;;;;;;;;;ii;i;;;;;i;;;;i;;iiiii
iiiiiiiiiiiiiiiiiiiii;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;iii;i;i;;;;;
iiiiiiiiiii;iiiiiiiii;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;i;;;i;;;;;;ii;i;;;i;
iiiiiiiiiiiiiiiiiiiii;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;i;;i;
iiiiiiiiiiiiiiiiiiiii;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;iii;;ii
iiiiiiiiiiiiiiiiiiiii;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;i;;;iiii;;
iiiiiiiiiiiiiiiiiiiii;,:;;;;;;;;;;;;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;;;;;;;,;;;,;;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;i;;;;;;;;;;;;;;;i;;;;;;iii;
iiiiiiiiiiiii;iiiiiii;,,,;;;;;;;;;;;;;,,;;;;;;;;;;;;;;;,,;;;;;;;;;;;;;;,;;;;;,,;;,,;,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;i;;;;i;;;;i
iiiiiii;iiiiiiiiiiiii;,,,;;;;;;;;;;;;,,,,;;;;;;;;;;;;,,,,,;,,,,;,,,,;;;,,,,;;,,,;,;,,;;;,,;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;i;;;;;;;;iii;
iiiiiiiiiiiiiiiiiiiii;;,,;;;;;;;;;;;;,,,,,;;;;;;;;;;,,;;;,,,,;,,,,,,;;;,,;,,,:,,;,;,,,;,,,;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;;;;;;;;;iii;;;iii;
;iii;iiiiiiii;iiiiiiii;,,;;;;;;;;;;;;,,,,,;;;;;;;;;;,,;;;,,,,;,,,,,,;;;,;;,,,,,,,,,;,,,,,,;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;i;;;i;;iii;;;
iiiiiiiiiiiii;iiiiiii;;,,;;;;;;;;;;;,,,,,,;;;;;;;;;;,,;;;,,,,;,,,,,,;;;,;;,,,,,,;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ii;;;;ii
iiiii;iiii;iiiiiiiiiii;,,;;;;;;;;;;,,,,,,,,;;;;;;;;;;,,,,;;,;;;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;;;;;;;i;;;;;;i;;;;;;i;i;;i
iiiiiiiiiii;iiiiiiiiii;,,;;;;;;;;;;,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i
iiiiiiiii;i;iiiiiii;ii;,,;;;;;;;;;;,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ii;;;;;;;;;;;;;;;;;i;;;;iii;;ii
iiiiiiiiiiiiiiiiiiiii;;,,,;;;;;;;;,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,iii;;i;;;i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;i;;;i;;i;;;i;;i;;;i;
iiiiii;iiiiiiiiii;ii;i;,,;;;;;;;;;,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;itjDEKKDGffLt;i;;;;i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;i;;;;;
iiiiiiiiiiiiiiiiiiiii;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;ii;itjjLEDDKKKEEDEKWWKEKEGi;;i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;i;;;;;;;;
iii;;iii;iiiii;iiiiiii;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ttGGGGEDDWWWWKEEKEEKWWKWWKDKEfi;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;i;;;i
i;iiiiiiiiiii;iiii;i;i;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;iGKWKKEKWWWWKKKWKEDKKWWKEKKKWWWWKKKELt;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;;;;;;;;;;;
iiiiiiiiiiiiiiiiiiiiii;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ifKKW#WWWEDEKEEKKWWWWWKKKKKKKWWWWWWWWWWWEj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,
iiiiiiiiiiiiii;iii;iiii,,,;;;;,;;;;;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;tLKKKWWWWEEEKKKKKKKWWWKKEKEKKWKWWWWWWWWKKKGti;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,
ii;iiiiiiiiiiiiiiiiii;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;EWWKWWKWKWWWWWWKKWKKKKKWWWKKKKWWWWWWWWWWWWKKEGDfi;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
iii;iii;iiiiiiiii;iiii;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;;;;;;;;iLWWWWWWKWWWWWKKKWWWKKWKKKKWWWWWWW##W####WWWWWWWKWKL;;;;;,;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,;;;;;;;;;;;
iiiiii;ii;iiiiii;iiiii;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;iijKWWWWWWWWWWWWWWW#WWWW######WWW####WWW#######WWWWWWWKL,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,;;;;,;;;;;;;;;;;;;;;;;;;;;;;
iiii;;iiiiiiii;iiiiii;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;jKWWWWWWWWWWWWWW##########W#####W########W#####WWWWWWWD;;,,,,::,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;,;;,;
iiiiiii;iiiiii;ii;iiiii,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;iiEWW#WW#####W##############################WW#W##W#WWWWWKf,,,,,,,,,,,,,,,,;,,,,,,,,,,;;;,,;;;;,;,,;;,;,,;;,;;;;;;;;;;;;;;;;;;;;;;;
;i;i;iiiiiiiiiii;;i;iii,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;;;,,,,,,,,ijKWWW##################################WWWWWWWWWWWWWWWWWWWKt,,,,,,,,,,,,;;,,;;,;,;;,;;,,;,,,;;;;;;,;;,;;,;;;;;;;;,;;;;;,;;;;;;;;;;;
;iiiiiiiiiiiiiiii;iii;i,,,;;;;;;;;;;;;;;;,,;,,,,,,,,,,,,,,,:,,,,::,,fWWW#####################################WW##WWW#WWW##WWWWWWKi,,,,,,,,,,,,,,,;;,,;;,,,,;;,,;;,;;;;,;,;,;;,;;;;;;;;;;;;;;;;;;;;;;;;,;
ii;iiiii;iii;iii;i;ii;i,,,;;;;;;,,,,,,,,,,,,,:,,,,::,:,,,,,:::,,:,,,GWWW##########################################WWWWWWWWW#WWWW#j,;,,,,,,,;,;;;;,;,;;;,,,;,,;;;;,;;,;;;;;;,;,,;;;;;;;;;;;;;;;,;;;;;;;;;
iiiiiiii;iiiiiiiiiiii;;,,,,,,:,,,,,,,,,,,,,,:,:,,,:,,,,,:,,,,,,,,,;;WWWW##################WWWW#W##################WWWW#WWW###WWWWE,,,,,,,,,,,,;,,,,;;;,,,,,;;,,;,;;,,;;;,;;;;;;;,;,;;;;;;;,;;;;;;,;;;;;;
iiiiiiiiiiiiiiiiiiii;ii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,ifEWW#########################################W##WW#WW#WWWW#WW#Wi;,,,;,;,,,,,,;,,;;;,;;,;;,,;;;;,;;;;;;,;;,;;;;;,;;;;;;,;;;;;;;;;;;;;;
iiii;i;iiiiiiiiii;i;;i;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;tGWWWW###################WWW#############W######WWW##W#WWWWWWW#WDi;,,,,,,,,,,,,,;,;,;;,;,,,,;,;,,;,;,;,;;;;;;;,;;;;;;;;;;;;;;;;;;;;;;;
;ii;iiii;;ii;iiii;i;iii,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,iijKKW#W###WWKWWW##########WWWWWWWWW########W########W##W##WWWWWWWWWi,,,,,,,,;,,;,;,,;,,,;,;,;;,;,;;,;,,;,;;;;;;;;;,,;;;;,;;;;;;;;;;;;;;
iiiiiii;i;iii;iiiii;;;i,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,ijDKDKW######W######WW###########WW###WWWW#####W#########W####WWWWWWG;,,,,,,,,,,;;,,;,,,,;;;,,;,;;,;,;;,;;;;,;;;;;,,;;;;,;;;;;;;;;;;;;;;
iii;iiiiiiiiiii;i;ii;i;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;tDKKEKW#######WWWW##############W###W####WWWW##############W#W##WWWWW;,,,;,,,,,,,;,,,,,,;;,;,,;;;,;;;;;;;,,;,;;;;;,;;;,,;;;;;;;;;;;;;;;;
ii;;;ii;i;i;ii;iii;i;;;;,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;ijGEKKKK#########WWW####W#W######W#WW##W####W#W##W############WWW###WWi,,,,,,,;,;,,,,,;;;,;,;;,,,,,;;;,;;,;;;;;;,;;;;;;;;;;;;;,;;;;;;;;;;
i;iiiiii;i;i;ii;i;iii;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,tjGEGEWWW##########WWWWKWWW########WWWW#W######W##############W#WWWWWWK;,,,,,;,,,,,;,;;;;;;;;,,;;;,,,,;;;,,;,,;,;,,;;;;,;;;;;;;;;;;;;;;;;
i;;i;i;;iiiiiiiiii;;iii;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;tjGEEEKWW################WWWW########WWWWW#########W############WWWWWWWi,,,;,,,,,,;,;,,,;;,;;;;;,,,;;;;,,,,;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;
iiii;;;ii;i;;;i;iii;iii;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;tGDDKKKKWW################WWWWWW#WWW##W#W#WW#######WW############WWWWWWD;,;,,,;;;,,;,,,,,,,,;;;,;,,;;;;;,;;;;;;;,;;;;;;;;;;;;;;;;,;;;;;;;
iiii;;;;;ii;i;i;;ii;ii;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;tDDDEKKKWW###############WWWWWWWW#WWW####WWWW#######W#############WWWWWKj,,;,,,,,,,;,;,,,,;,,;;,,,;,;;,;;;;;;;,;;;;,;,,,;;;;;;;;,;;;;;;;;
i;i;;;i;i;iiiiiiii;i;;i;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;ifDEKKKWWWW############WWWWWKKKWWWWWWWWWW###WW########W###########W#WWW#WE;,;,,,,,,,,,,,,;,,,,,;;;,;;;;;;;;,;;;;;;;;;;;,;;;;;;;;;;;;;;;;;;
iii;;;i;iiii;;;iii;i;ii;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;tjfDWWWWWW##########WWKKKKKEEEKKKKKKWWWW####WWW##########W#########WWWWWWi,,,,,,,,,,,,,,,,,,,,,,;,,;;,;;;,;;;;;,;,;;;;;;;;;;;;,;;;;;;;;;;
;;;i;ii;;ii;;ii;;;ii;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;jtLDWW###########WWKEKEEKEDDEEKKKKKKWWWW###WW###################W##WWWKWi,,,,,,,,,,,,,,,,,,;;;;;;,;;;,;;;,;;;;;,;;;,;;;;,;;,;;;;;;;;;;;;
i;i;i;iiiii;i;;;;i;;;i;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;itfGKWW##########WKEDDGDDKEDDDDEEKKKKKWWWWW###W#############W##WWW#W#WWWWL;,,,,,,,,,;,,,,;,,;;,,,;,;;;;,;;,;;;;;;;;;,;;;;,;;;;;;;;,;;;;;;
i;;;iii;;;;i;;i;i;;i;ii;:,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,;ijjGKWW########WKKDGGGGDGDEDGDDDEEKKEKKKWWW#W##W#WW####W##########WW##WWWW,,,,,,,;,,,,,;,,,,;;;,,,,;;;;;,;;,;;;;,;;;;,;;;;;;;;;;;;;;;;;;;
i;;;;;;iiii;ii;;i;;;;i;;,:,,,,,,,,,,,:::,,::,,,,,,,,,,,,,,,,,,,iifDWWW########KEDGGGDGGGDGDDGDDDDDEEEEKKKKWW##W##WW###WWWW###W########WWW,,,,,,,,,,,,,,,;;,;;;,,,;;;;,;;;;,;,;;;,;;;;;;;;;;;;;;;;;;;;;;;
;;i;i;;i;;i;;;;ii;ii;;;;,,,,,,,,,,,,,,,:::,:::,,,,,,,,,,,,,,,,,;jjfWW########WEGDGGGGGGGGDDDGDDGDDEEEKKKKKWWWWWW##W####W#W#############WW,,;;;,;;,,,,,;,;;,;,,;,,,;;;;,,;;;;;;;;;;;;;;;;;;;;,;;;;;;;;;;;
;;i;;;;;ii;;;;;;;;;;i;;;,,,,,,,,,,,,,,,:,::,,:,,,,,,,,,,,,,:,,,,,LfWWW######WDGGGLGLGGLGLGLGGGGGDDDEDEEKKKKWWWWWW##WW####W##############W,;,;,;,,,,;,,,;,,;,,,;,,;;,;,;,;,;;;;,,;,;;;;;;;;;;;;;;,;;;;;;;
;ii;i;i;;;;;;;;;ii;;;;;;,,,,,,,,,,,,,:,,:,::::,,,,,,,,,:,,,,,,,;i;LWW######WEGGGLLLLGLLLLGGGGGGGGDDEDEEEEEKWWWWWWWWW######W#############W;,,;;,;,,,,,,,;,;;;,;;,;;;,,;,;,;;;;;;;;;;;;;,;;;;;;;;;;;;,;;;;
;;i;;;;;;;;;;;;;;;;;;;;;,:,,,,,,,,,,,,:,,:::,:,,,,,,,,,,,,,,,,,,;;G########DGGLLLLGLGLLLGGGGGLGGGGGDDDDDEEEEKKWWWW#W#######W############W,,,;,,,;;,;,,,,,;,;,,,;;,;;,;,;;;;;;;;,;;;;;;;;,;;;;;;;;;;;;;;;
;;i;;;;;;;;;i;;;;;;;i;;;,,,,,,,,,,,,,::,::,,,,,,,,,,,,,,,,,,,,,,;;L#######WDGLLLLLLLLLLLGLLGGLLGLGGGGGGDDDDEKKKWWWW#W###################W,,,,,;,,,,,,,,,;,;;,,,;;;;;;;,;,;;;,;;,,;;;;;,;;;,;;;;;;;;;;;;;
;i;;i;;;;i;;;i;;;;;;;;;;,,,,,,,,,,,,,,,,:::,,,,,,,,,,,,,,,,,,,,,,;t#######KGGLfLLffLfLfLfLLLLGLLLLLLLGGGDGDDEKKKWWWWW##################WK;;,;,,,,,,,;,,;;;,,,,,,;,;;;,,;,,;;;;,;,;;;,;;;;;;;;;;;;;;;;;;;
i;;;;;;i;;;;;;i;;i;;;i;i,,,,,,,,,,;,,,::::::,,,,,,,,,,,,,,,,,,,,,,;#######EGLfLffffLfLLfffLLfLLLLLLLLLLGGGDDEEEKKKWWWW#################WD;,,,;,,,,,,,,,;,,;,;,;;,;,;,,;;;;;,;;;;;ii;;;;;;;;;,;,;;;;;;;;;
;;;;;;;i;;;;;;;;;;;;;i;;,,,,,,,,,,,,,,,,:,:,,,,,,,,,,,,,,,,,,,,,,;t#######ELLfLffffLfffffLLffLLLLLLLLLLGLGGGDEEKKKKWWW#####W############K;,,,,,,,;,,,,,,,,,,;;;;;;,,;;;;;,;;,;,;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;i;;;;i;;;;;;;;;,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;E#####WGLffjfffffLLffLLLLLLLLLfLfLLLGGGGGDDEEKKKKW##################Wf,,,,;,,,,,;,;;,;,,,,;;;;;;;;,,;;,;;;;;;;;,;,;,;;;;;;,;;;;;;;;;;
;;;;;;;;i;;;;;;;;;;;;;;i,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,f#####WGLfffffffLLLLGLLLLLLGGGDDKEEEDEEEEDGDEEEKKWWW##W###W##########L;,,,,,,,,,,;,;,;,,,,,;,,,,,,,;;;;;;;,;;;;;;;;;,;;;;;;;;;;;;;;;;
;;;;;;;;;i;;;;;;i;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,i#####KGGLGGDDEDGGGGDGLLLLGDEDKWWWWWWKKKEEEDDEDEEKKWWW#############W#L,,,,,,,,,,;,,,,,,,,,;,;,,;,,;;;;,,,;;;,;;;;;,;;;;;;;;;;;;;;;;;;
;;;i;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,t####WEGGDDEEWKKEDDEDGLLGGDEEEKKKKWWWWKKKEKEEDDDEKKWWWW##############j;;,,,,;,,,,,,,,,,,,,;,,;,,;,,;;,;,,;;;;,;;,;;;;;;;;;;;;;;;;;;,;
i;;;;;;;;;;;;;;;;;;;;;;;,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;DWW#WDDEEKKKWWKKKEDDDDDGGEEEKKKEEEEEEEEEEEEEEDDDEDKWWWWW############f,,,,,,;,,,;,,;,,,;;,,;;;;;;;;;;;;,;;,,,,;,,,,,,,,,,,,,,,,,,,,,,
;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,jG##KKEEEEEEEKKKKKEDDDDDDDEEEEDDGLGGDDDEEEEEEEGDDGEWWWWW#########W##E,,,,,,;,;,,;,;,;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
;;;;;;;;;;;;;;;;;i;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,iiEWKKEEEEKKKGDEEEEEEDDDDEEEK###WWWWWWWWWWKEDDDGDGDKKWW#############E,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;LWEKKWWWWWW#WKEEEEDDDDDEEW#WKEDDGDGDEKW##WKEDGGGGEEWWW############G,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
;;;;;;;;;;;;;;;;;;;;;;;;,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,tW#WKEGLfLLLGGDKWKEDDDGDWWDDDDDDGGDLDGGDDW##WGKKKKKKW##############t,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,
;;;;;;;;;;;;;;;;;;;;;;;;;,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:###fDKDLLGDDDDDDDDK#KKKDWKDEEEEKW##WW#WKEED##WDWKW#WWWWWW########WW#,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,:,,,,,,,,,,,;,;;;;;;;iiiiiii
;;;;;;;;;;;;;;;;;;;;;;;;,,:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,###fEGGDKWW##WKEEEEW##WWWDDDEKK###WKEDDKKKE#LGDEEEKWW######W##W##WWD,,:,,,,,,,,,,:,,:,,,,,,,,,,,,,;;;;;;;;iiiiiiiiiiiiiiitittttitiii
;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,E#KEKGGKWW####WKEEEK#EGDWDDDEK##KKEDGGDDDDD#DDDEKKKKKWW#######WKK#Kf,,,,,,,,,,,,,,,,,,;,,;;;;;;ii;iiiiiiiiiiiiiitiiiiiiiiitiitttiitt
;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,::,::::,,,::;EfKEKEDDEEKKKKKEDEWDGDKEDDDEEEEEEEEEEDGGL#GDEEEDGGDKWWWWWKWDLLfft;;;;;;;;;;i;iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiitiitititii
;;;;;;;;;;;;;;;;;;;;;;;;;,::,,,,,,:,,,,,::,,,,::,:,,,:,,::::::,::::,::K;jDDDDDGGDEEEEEGKKLffDWEGGDDKKKKKKEDGGLLWDDDGGLGGGKWWWWEEDGKWKDtiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiitiiiiiiitiiiittiiti
;;;;;;;;;;;;;;;;;;;;;;;;;,:::::,:,,::,:,,:,,,:,:,::,::,,::::,:,:,,::,:K;fGGDEEEKKKKKKGGWELjfGWEDGGGGEEEEDDGLLGGWDGLLLLGGGKWWWKDDDEKKWKLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiitiiiiiiiiiiitttitiitii
;;;;;;;;;;;;;;;;;;;;;;;;;,,:,:::,,:,::,:::,::,,,,:,::,::,:,:::,:,::,,:D;ffLLLDEEKKDGGGDWGjjjLWEEGLLLLLLLLfLLGGGELLLLLLLGGKWWKGGDEKEEKKEjiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiitiiiiiiitiiiiiiiiitiiiiiiit
;;;;;;;;;;;;;;;;;;;;;;;;;,:::,::,,::::,::,:,,::,,,:,:,,:,,,,,,,,,,,,;;tjffjfLLLGGGGLGGWWfjjffDKDGGGLLLLLLLLLLLWfLLLLLfLGDEKKDGGDKEDGEKEGiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiititiiiiitiii
;;;;;;;;;;;;;;;;;;;;;;;;;,,::,,:::,:,:,:,,,,,,,,;,;;;;;;;;;;;;i;iiiiiiiKLfffjffLLLLLGLWDftjjjfKKGLGGGLLLLLLGLLWffffLLLLLGDKEGGDDGDGLDKKDiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiittiiii
;;;;;;;;;;;;;;;;;;;;;;;;;,,,:,,,,,,,,,,;;;;;;;;;;;i;;;;i;ii;iiiii;;ii;;WfffjffffLLGGGGKGjtjjjfDKGGLGGGLLLLLLLGGffffLGLLGGDKDGGEDGGLLGEEGiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;iiiii;iii;i;iiiiiiiiiiiiiiiLKLjjfffLLLGLLWGfjtjjjLLGKDGGGGGGGGLGWEfffLfLLLLGLDEGGGDKKGGGLEGLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ii;;i;i;ii;i;iiiii;;iiiiiiiiiLLEGjffLLLLDWEDfjtjjjjfLLDKKKEDDGEWWKDGLLLLLfLLLGGGDLGLDWKKEELDDtiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;i;ii;;;i;iiiiii;iiiiiiiiiiiiiiiiiiiiLLffEEWWWKDDDEGfjffjfjfffLEEKKEKEEEEEDDGGGGDGGGLGGGDLLLLEEKKEGEG;iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii;i;;;;;;;;;;;,,;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;iii;i;;iii;;iii;i;iiiiiiiii;iiiiiLLLLDEEDDDDDDELfffffffffjjDEKEKEEDDDGDDGGLGDGGLGGGGDLLLfEEEKKLEtiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii;i;;;;;;;;;,;;;,;;,;,,,,,,,,;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;i;;ii;;iiii;iiiiiiiiiiiiiiiiiii;LLLGDDEEEEEEEfjLLLLGGGLLffLGEEDEDDDGDGGDDGGDDDGGLGDDGLLfDDEEELGiiiiiiiiiiiiiii;iiiiii;;;;;;;,;,;,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;
;;;;;;;;;;;i;;iiiii;iti;;;;;;;;;;;;;;;;;iiii;;iiiiiiiiiiiiiiiiiiiiiiiiiLGGDDDDDEDDDLfLDDDDEEEEKEDDDEDEEEDDDDDDEDDDDDDGGGGGGLLGDDDDEDLjii;;;;;;;;,;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;,;,;;;;;;iiiiiiiiii
i;ii;;i;i;ii;iiiiiiiiti;;;;;;;;;;;;i;;;i;;iiii;iiiiii;;i;iiiiiiiiiiiii;LGGDDDEDDDDDGLDEEEKKKEW#WKEKDDEEEDEDDDDEDEDDEEDGGGGGLLDDGDDGLG;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,;,,;;;;;,;;;;;;;;iiiiiiiiiiiiiii;ii;
i;;;;;;;iiiii;iiiii;ittt;;;;;;;;;;;;i;;;i;iiii;iiii;ii;iiii;ii;i;i;;;;;LDDDDDDDDDDDDEWWWKKKKWWKWKKEDDEEKEEDEEDDDDEEEDGDGGGLGGELffGGDG,,,,,,,,,,,,,,,,,,;,,,,;,,,;;;;;iiiiiiiiii;ii;i;;;;;i;;i;;;;;;ii;;;
ii;;;;;;;;ii;;iiiii;itttti;;;;;;;;;;;;i;;i;i;iiiiii;;ii;i;;;;i;;;;;;;;;tDEEEEEDDDEDDDKKKKWWWWKEEEEDGGDDEKKEEEEDDEEEDDDDGGGLGGLGfLEDG,,,,,,,,,,;;;;;;i;iiii;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;i
i;;ii;ii;;i;;;iiiiiiittttti;;;;i;;;;;;;;;;;ii;;;;i;;;;;i;;;;;;;;i;;iiii;DDDEEEEEKEGGGEDDEKKKKEDDGDDDDDDDEKKEDDDDEEDDDDDGGGLGLfLfffGt;;;;;;;;;;;,,;,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ii;;;;;;;;i
;;iii;;;;;;;;;iiiiiiitttttt;;;;i;;;;;;;;;i;;i;i;;i;;;;i;;;ii;iii;;;;;;;,DDEEEEDKKDGGGGGGDEEEEDDGGGGGGDDEEEKEDDDDEEDDDDGGGGLLfLfffLt;;;;;;,;,,,,,,,,,,,,,,,,,,;,;;,;;;;;;;;;;;;;;;;;;;;;;i;;;;;;;i;;;;;;i
;;;;;;;;;;;;;iiii;iiitttttti;;;;;;;;;;;;ii;;i;iiiii;;;;;;;;;;;;;;;;;;;;,fGDEEEDEEDDLLGLLLLGLLGGGGLLLLGGDEEEEEDDDDDDDGDDGGGLGLLLGLi,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiii;iiiiiiiiiiiiiiiitttttttii;;;;;;;;jjj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,iGDDDDDDEDGffLDEEEEEKKKKKKEDGLLDEDKDDEDGDDDDGGGGLLGEDDEE;,,,,,,,,,,,,,,,,,,,,,;,,,,,,;,,;;,;;;;;;;;;;;;;;;;;;;;;;;i;ii;;i;ii;iii
iiiiiiiiiiiiiiiiiiiiittttttttti;;;;,;;GLL;;;;;;;;;;;;;;;;;;;;;;;;;iiiiiiifGEDDGDGGLDKWWWWKKWKWKWWWWWWKEKDEDDGGDGDGDGDGGGGGGEEj,,,;,,,,;,,,,,,,,,,,,,,,,,,,;,;;,;,,;;;;;;;;;;;;;;;;;;;;;;;ii;;;;;;;i;;;ii
iiiiiiiiiiiiiiiiiiiiitttttttttt;;;;,,;fff;;;;;;;;;;;;;;;;;iiiiiiiiii;;;;;iGDDGDDDGGKWWWWGGDLjKDKEKWWWWKEDDDDDDDGGDDGGGGGGLDKEi,,,,;,,,,,,,,,,,,,;,,,,,,,,,,,,;,,,;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;iiiii;
iiiiiiiiiiiiiiiiiiiiitttttittittiii;;;;;;;iiiiiiiii;;;;;;;;;;;;;;;;;;;;;;;GDDGGGDDKWWWEGtttttfLLDDEW#WEDDDGDDDDGDDGDGDGGGLDf;;;;;;;,,;,,,,,,,,,,,,;,,,,,,,,,;;,,;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;
iiiiiiiiiiiiiitttiiiiittttttitttjii;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;LGGDGGGGEW#WGLjjLLDEDWKWKEEGDDDDDDDDDDDGDDDDGGGGD;;;;;;;,;,,,,,,;,;;;,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;;;;
ii;iiiiiiiiiiitttiiiiittitiitittjti;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;jGGGLGGGGEKWDLDW######WEDDGDGDDGDDDDDDDGDDDDGGGGDi;;;;;,;,,,,,,;,,;,,,,,,,,;,,,,,,;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;
iiiiiiiiiiiiiittttiiiitittttiiitjtt;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;GGGGLLGLLLLGWWEEEELGDGGGGDDGGGGDDEDDDDDDDDDDDGDj;;;;;;;;;;,;,,,;,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiitttttiitiiiittiittjtt;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;GGGGGGGfGGGLLLLLGGLLLDEDEDGGGLGDEEEDDDDDDDDGGLD;;;;;;;;;;;;;;,;,;,;,,;,,,,,,,,,;;,;;;;;;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiittttttitttitititttjjt;;i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;tDGDDGGLLGDDDGLLLGDEEEEEEGDGGGGDEDDDDDDDDDDDGGG;;;;;;;;;;;;;;;;;,,,,;,,,,,,,,,,,,,,,,,,;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiititttttttiitttttttjjj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;LDDDDLLLLEEEEDDDDEEKKKKDGGGGGGDEEDDDDDDDGDGGGG;;;;;;;;;;;;;;,;,;,,,,;,,,,,,,,,,,,,,,,,;,,;;;;;;;;;;;;;;;;;;;;;i;;;;;;;;;;;;;
iiiiiiiiiiiiiitttttitttiiititittjjt;;;i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;DGDDGLLLGKKKKWKWWWWKEDDDGDGGGGDDDDDDDDDEDDGGf;;;;;;;;;;;;,;;,,;;,;,,,,,,;,,,;,,,;,,;,,;;;,;;;;;;;;;;;;;;i;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiitttttttttittiittitjfj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;GDGDGGGGGDEKWWWWWWKKEEDGDDDGGGDDDDDDDDDDEDGGi;;;;;;;;;;;;;;;,;,;;,,,,,,,;,,,,;,,,,,;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;;;;
iiiiiiiiiiiiiittttjttttiitttttitjjj;;ii;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;iDDDGGGGGDDKKWWWKKKEEDDDDDDGGGGDDDEDDEEEDGLGi;;;;;;;;;;;;;;;;;;,;,,;;,,,,,,;,;,,,,,,;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiitjjjtjttttiittttttjfj;;ii;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;DDGGGDGGDDEKKWWWKEEDDDGGDGGDGGDDDDDDEEEEGGGi;;;;;;;;;;;;;;,;;;;;;,;,,;,;,;;,;,,;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ii;iiiiiiiiiitttjtttttiittttttitjfj;;;i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;tDDDGGGGGDGGDDDDDDDGGLLGLGGGDGDDDEEEEKEDGGL;;;;;;;;;;;;;;;;;;;,,;,,,,,,,;,,,,,,;;,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiitjttttttttttitttittjjt;;;i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;tDEGGLGLfLLLGGGDDGGLLLLLLGDGDDDDDEEKKEEDGGG;;;;;;;;;;;;;;;;;;;;;;;,;;,,;,;;;;,;,;,;,;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;i;
iiiiiiiiiiiiitttjttttttittttttitjjt;;ii;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;LDEDGLLLffLGEKKKKKKDGfLLGGDDDDDDDEKKKEEGGGG;;;;;;;;;;;;;;;;;;;;;;;,;,;;,,,,;;,;;,;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;
iiiiiiiiiiiiittijttttttittttttttjfj;;;i;;;;;;i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;LfWKDGLLLDKKKKKKKKWKKKKDGGDDDDDEEKKKKKEDDGLL;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;,;,,,;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiitttjttttttttittttitjjj;;;i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,DLWKDDGGKKWKWKKKKWWWWKWKEDDEDEEEKKKKKKEDDGLG;;;;;;;;;;;;;;;;;;;;;;,;;;;;;,;;;,,;;,;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiijjjjtttttttttttttttjfj;;;i;;;;;i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;iLGG##GEKKWKWWKWWWWWWWWKWKWKEEEKKWWKKKKEEDDGGL;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;,;;,;,,,,;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiitjjjtttjtttittttttttfj;;;i;;;i;i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;LLDE##GEWKKWKKWKWWWWWWWWWWKWKKKKKKKKKKKEDDGGGf;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;iii;
iiiiiiiiiiiiittjfttttttttttttttttjji;;ii;;;;ii;;;;;;;;;;;;;;;;;;;;;;;;;;;;LffLEW#GKWWWWWWWWWWWWWWWWWWWWKWWKKKKKKKEEDDDGGDi;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;i;i;
iiiiiiiiiiiiitttjttttttttitttitttjj;;;i;;;;;;;;;;;;i;;;;;;;;;;;;;;;;;;;;;jGGGDEW#EWWWWWWWWWWWWWWWWWWWWWWKKKKKKKKEEEDDGGGEK;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;,;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;ii;i;;
iiiiii;iiiiiitjjjiittttitttttttttjji;;ii;;i;;;;;;;;;;;;i;;;;;;;;;;;;;;;;LGGGGLKWWKWWWWWWWWWWWWWWWWWWWWWKWWKKKKEEDEDDDDDGWWE;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiii;iiiiiiitffjiiitttttttittttjjji;;i;;;;i;;;;;;;;;;;;i;;;;;;;;;;;;;;;GGLGGLWWWWWWWWWWWWWWWWWWWWWWWWWWWWKKEEEDEDDGDDGGWWKt;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;i;;;;;;i
iiiiiiiiiiiiijLLtiiitttttttttttttjji;;i;;i;;ii;;;;;;;;;;;;i;;;;;;;;;;;;jLffGGGWWWWWWWWWWWWWWWW##W#WWWWWWWKEDDDDDDDDDDDDK#WWKt;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;
iiiiiiiiiiiiitGDLiittttttttttttttjji;;i;;;;;ii;;;;i;;;;i;;i;;;;;;;;;;;tGLGDDGGWKWWWWWWWWWW#W#WW#WW#WWWWWWKDGDGDDDDDDDDD##WWKK;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;iii;;;;i
iiiiiiiiiiiiitLDDjittitttttttttttjji;;i;;;;;;;i;;;;;;;;;;;;i;;;;;;;;tjfGLGGDDDWWWWWWWW#WWW#WW##WW#WWWWWWWWDGGGDDDDDDDDD##WWKKt;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;i;;;;;;i
iiiiiiiiiiiiitjLDLjttttttttttttttjft;;i;;i;;;;;ii;;;;;ii;;;;;;;;;;LLGGGGLGGDDDKWWWWWWWWWW####WW#W#WW#WWWWKGGGGGDDDDDDDD###KWKK;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;iiii;i;;i;
iiiiiiiiiiiiittLDfjttttttttttttttjft;;i;;;;;;;;;;;;;;;;;;;iiijjffLLGGGGGLGGDDEKWWW#W#W#W#W##W######WWW#WWWGGGGGGDDDDDDE###WW#KG;;;i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;;;;;;;;i;;
iiiiiiiiiiiiiitfLtttttttittttttttjjt;;i;;;;;;;;;;;;;itjjffLLLGDDDDDDDDGGDDGDDEKWWW#WW######WWW##WW#W#WWWWWDDDGGGGGDDDDK##W#WWKKG;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;i;i;;i
iiiiiiiiiiiiiitjLjtttttttttttttttjjt;;i;;i;;;;;ittjjLfLLDLGDGGDDDEDDDELLDDDDDEEWWWWWWWWW####W####W##W#WWWWDDDDDGDGDDDD###WWKEKWK,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;iii;i;;;
iiiiiiiiiiiiiitjftttitttttttttttttft;;i;iijjfffLLLDGDDDDDDDDDDDDDDDDEEDEEDDEDEEKWWWWW#W##############WWWWWEEEDDGGDDDDE##W#WWKWKW;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ii;;;;i;
iiiiiiiiiiiiiiijjtttttittttttttttjft;tfffffLGLGGGDDDDGDDEEDEEEEEKKEEDDDEEKGGDEEEKWWWWW################WWWWEEEDDGDDDDEK#####WWKKKj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ii;;;;
iiiiiiiiiiiiiiitjttittittttttttttjLffLLLGGDDEEEEEEEKEDEEEEDDDEKDGEEDEDDEEEKDDEEKWWW##W##WW#W#########WWWWWKEEEDDGDDDE###W##WWEWKK;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;
iiiiiiiiiiiiiiitjtttitittttttiiffffLLGDDEDDEELDGGDEGDDDDGDDDEKDEDKEEKDLDEEKEDEKKWWWW#############W###W#WWWEEEEDDDDDEE######WWKKKK;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;
iiiiiiiiiiiiiiittttititttttttfDGGGGDDDEKKKKKEKKKEEDDEEEDEEEEKEDKEEEEDGDEKKEKKEEKWWWW####W####W######WWWWWWEEKEDDDDDEK########WKWW;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;i;;;;;
iiiiiiiiiiiiiiittttittitttifEKWEDELLLLLLLGGDEEEKKWEKKKEEEKEKWDEWKEEKGGGEEKDEKEDEWWW##################WWWWWEEEEDDDDEKW#######WWWKW;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ii
iiiiiiiiiiiiiittttiiititttfLDDDEGDGGGGGGLGDDEDGGDEEKKKEEKKKKWEKKKEEKGGGEEKEEKKEEKWWW####W############WWW#KEDDEDDEEEKW########WWKKj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiiitjtttiiittGDGGGELEDDDGDDDDEEDEEEKEDDDGDKKKKWKKKKKKKKWDGGKDKKEEKKEKWWW##################W#WDDDEDEDDEKWW########WWWWWt;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiiitttttttiLDDDEDDDKGEEDDDEEEEKEEEEKKEEEDDEEEDEEWKWKKKWKEDGKKKDKKKKEKWWW###################WKDDEDEEEEKKWW#######WWKKKKKG;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;;
iiiiiiiiiiiiiiittttttiGDDDEDEDDDDDKEEEEKKKKKEEEKKKKEEEEEEEEKWEEEEEKKDEEEKKEKKKEKEKW#####################EEDEEEEEKEKWW#####WWWWWKWKKKGi;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;
iiiiiiiiiiiiiiiittttiGDDDEDDDDEDDEKKEEEKKKKKKEEEKKKKEEEEEEEKKKEEEEKKDDKEKKEKKWEEEKW#W###################EEEEEEEEEKKWW######WW#WWWWKWEDji;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiiiittttjDDDDDEEEEEEEEDKEEKKKKKKKKKKWKKWKKKKKKKKKKEEEKWKEDDWKKKEWKKEEWWWW###############WWKKKEEEEEEEKKWWW######WWWWWWWEKKEDGLti;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;;;;;;;i
iiiiiiiiiiiiiiiittttEDDDEEDEEEKEEEEKKEKKKKKKKKKKWKKKKKKKKKKWKKKEKWWKWEDEKWKKWWKEEWKWW###############WKKKEKEEEEEKKKWWWW#####WWWWWWWWKKDEEEDGGi;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiiittttDEEEEKEEEEKKKKEEEDKKKWKWKKKKWWWKKKKKKKKKWKKKK#WWWDDGWEKKWWKEEEKKWWW##############WWKKKKEEEEKKKKWWW######WWKWWWWWWWKEEEDEDGEG;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiiitttiDEKEEKKKKKKKKKEKEEWKWWWWKKWKWWWWWKWKKKKKWEKKKWWWKDDGWKEKKWEKEEKKWWW######W#######WWKKKEEEKEKKKKWWW######WWWWWWWWWWWEDDEEDDDGL;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;i;;;;;;;
iiiiiiiiiiiiiiiitiLKKKKKKKKWKKWKKKKEEKKWWKWWKWKWWWWWKWWWWWWWKKKKWWWKDGGWWEKEKKEEKKKWWW######W#######KWKKKEEEEEKKKKW##########WWW#WW##WKKEEDEEDDEEDti;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iitiiiiiiiiiiiiitfEEKKWWKWWKWWWWKKKKKKWWWKWKWKKWWWWWWWWWKKWWKKKKWWKEDDGWWEEKEWWWKKKWWWW##WDDGDDDDGDEWWKKKKKEEEKKWW############WW#WW##WKKKKKKEEDDEEEDGt;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiiiitEEKWKKWKWWWWWWWKKKKKKWWWKWWWWKWWWWWWWKWKKWWWWWW#WKKDDGWWKEKEKKKKEKWWKWW#ttttttttjjtD#WWKKEEEKKK#############WWWWW###WKKKKKKEDGDEEDEDEf;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiiiitEEEDDEEEKWWWWWWWWWKKKKKKKWKKKKWWWWWKWWWWWWWWWWW#WKEDEEWWWEKKKWKKKEKKKWWtttttittttitjD###WWWWW################WWWW###WKWEKKKKDEKEEDDEDEDGf;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiiiiiEDDDDDDEEEKWW#WWW#WWKKWWEKKKEKKKWWWWWWWKWWWWWWW#WWGGGGKWKKEKKKKKKKKWDitfffffjjjjjfffjf########################WWW###WWKKKKWKKWKKKEEDDDDEDDft;i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i
iiiiiitiiiiiiiiifDDEEDEDEEEEKEWW##W#WWKW#KWKKKKKWKKWWWWWWWWWWWWW#WKLGDEWWWWEEKKKKKKWDtjfDGDDDDGGLGGLLjjG###################WW#W##W###KWWWWWWKWWWWKKKKKEEDEEDEEj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiiiifDDDEEEEEEEEKEWKW###WWKKWKKKWKEKKKKKKWWWWWWWWWWW#WKLDEEWWWKKEKWKKKKKfffGDEDDDDDDDGGGLfjj###################W#WW######EKEKWWWWWWWKWKKKKKKEEDDEDEj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiitiiiDDDDDDEEKEKEEEKKKKK#WWWWWWKWKWKKKKWKKWKKKWWWWWWW#WEGEKKWWWWKKEKKKKKKEGEKKKWWKKKEKEEDGLfjLW###W############WWWWWWW###WKKKKEEKEEEKKEEEEEEKWKKEEDDEEj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiitiiiiitGDDDEEDEEKKKKKKKEEKKWWW#WWWWKKWWKKWKKKKWKKKKWKWWW#WGKKWWKWWKKEKKKKKKKEKKKW########KEEDGLLff################WWWWWWW###KKKWKKKEKKKEKKKEEEEEDDDGGDEEEEEi;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiitiDDEKKEEKEWKKKKKKKKEKEWWKW#WWWKKWWKKWKWWKWKKKKWKWKWW#DKWWWWWWKKKKKEEKKKKWWKW####W####KEDGGGfjG###############WWWWW#####KKWWKKKKKKKKKKKEKEKEEEDDEEDDDEEEL;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiiDDDKWKKKKWKKKKKKKKKKKWWKKW#WWWKWWWWWWKWWWWKKWWKWKWWKDEKWWWWKKEEKKKKKKKWWKKLfDE#W####WEDDGGLfj#########W#####W#WW#####WKKWWWKKKKKKKKKKKKKEKEEEKKEEEEDEKEi;;;;ii;;;;;i;;;;;;;;;;;;;;;;;;;;;;
iiiiiiiiiiiiiDDEEKKWWWWWWWKKKKKKEKKKWWKKW#WKWWWWWWWWWWWWKKWKWWK#KEEKWKKKWWKGKKKEEKKKKKWLitjjfLK####KEDDGGLjj################W######WWWWWWKKKKKKWKKKKKKEKEKKKKKEEDEDDDE;;;;;;;;;;;;;;;;;;;;;iiiiiiiii;;;;
iiiiiiiiiiiiiDEEEEKWWWWW##WWKKWKKWKKWWKKWWWWWWWWWWWWWWWKKWWWWKW#EGGEWWWKWKWKWKEEWKWKKKGtjjjtjtjjLW##KEDDGGfjGW#########WW######WW#WWWKKWWKKKKKKWKKWKKKKKEKKKKWKKEEEEDDG;;;;;;;;;;;;;;;;;iii;;;;;;;;iti;;
iiiiiiiiiiiifEDEKKKKW##W##WWWWWKKKKKWWWWWWWWWWWWWKWWWWWWWKWWWWW#EDEKKWKWWKWWWWKKWKWKKKfjfjjjtjtjjLDWKEEDGLfjfD########W########WW#WWWWWWWKWKKKKWKKWKKKKKKKKKKWWKEEEEDEDt;;;;;;;i;;;;;;;;i;;;;;;;;iiii;;;
iiiiiiiiiiiiEEEEKKKKWW##WW#WWWWWKKKKWWWWWWWWWWWW#WWWWWWWWWWWWW#WW##WWWWWKWWWWWKKW#WWWKLLLLfffjjjjtttfGDDGLLfjt########WW######W###WWWKWWWWWKKKKWWWWKKKKKKKKKKWWKKKEEEEEKf;;;;;;;;;;;;;ii;;;;;;;;;;iii;;;
iiiiiiiiiiiiEKKEEWKKKWWW#W###WWWWWKWWWWW##WWWWWWWWWWWWWWWWWWW##W######WWWWWWWKKWWWWWWDGDDDDGLfLffjjjtttittjjffE#######WWWW#WWWWW##WWWWWWWWWWWKWWWWWKKKKKKKKKKWWWKKKKEEEWEi;;;;;;;;;;;ii;;;;;;;;;;;;ii;i;
iiiiiiiiiiijKKWKEKKWWKWW##W#####WWWWWKWWW#W#WWW#WWW#WWWWWWWWWWWWW#######WWWWWWWKKKW##fEEKKEEDDGGLffffjjttiitjLG######WWWWW###WWW#WWWWKWWWWWWWWWKWWKKKKKKKKKKKWKWWKKKKEKWEj;;;;;;;;;;i;;;;;;;;;;i;;;ii;;i
iiiiiiiiiiiGKKWWKKKWWWWWWW#####WWWWWWWW#W##WW###WWW##WWWWWWWWWWWWW########WWWW#KKWKW#LEKKKEKEDGGGLLLfjjjtttijfG######WWWWW###WW##WWWWWWWWWWWWKWWWWWKWKKKKKKWWWWWWWKKWEKWEL;;;;;;;;;;i;;;;;;;;;;;;;;iiiii
iiiiitiiiiiKKWW###WWWWWWWWW#######WWWWWWW##W####WWWWW#WWWWWW#WWWWW##########WWWKKKWWKDKKKWWKEDEDDDGLfffjjjjttjL######WWWKKWWWW###WWWWWWWWWWWWKWWWWWWWWWKKKWWWKWWWWWWKEWEEE;;;;;;;;;i;;;i;;;;;;;;;i;iii;;
iitiiiiiiijKWWW#EKK#WWW####W#W#####WWWWW########WW#####WWWWW#WWWWW############WWWWWWWEKKKW##WWDDEDGLLfffLLffjjf######WWWKKWWWW###WW###WWWWWWWWWWWWWWWWKKWWWWWWWWWWWKWKWEEKt;;;i;;;i;;;i;;;;;;;i;i;;iii;i
iiiiiiiiiifWWWEDDKKKKKKWWWWW###############WW####W##W###WWWW#WWWWW###################KKKW######KEDGfffffLLGGfff####WWWKKKKW#####WWWWWW#WWWW####WWWWWWWWWWKWWWWWWWWWWWKWKEKE;ii;;iii;;;;;;;;;;iiiiiiitii;
iitiiiiiiifKWEDEEEKWKKKKKKKWWW#W#####W#####WWW#W#W####W#W#WWWWWWWWWW##################WWW######WEffjjjjjfLLGfff####WWWWKKKW#####WWKKWKWWWWW##W#WWWWWWWW#WWWWWWWWWWWWWW#KKEEii;i;;ii;i;;;;i;;ii;;iiiii;;;
iittiiiiiiDWGDEEEKEKWWKKKKEKEKKW############WW#WKW###W#WW###WWWWWWWW#W################jtjjjjtjttjttttiittjLGLLfW###WWWWWWK######WWKKWWKWWKKWWKWWKKKKKWKKKKKWWWWW#WWWWWWKKKKG;iii;i;;;ii;;;ii;i;iii;iiii;
iiiiitiiitGKDEKEKKKKKWWWWKKKKKKKWW#######W#WW##KKWWWW#WW####WWWW#WW#WW###############tttttjjjjttttjttttiitfLGLfE##WWKWKWWWW##W#WWWWKKKKWKKKWWKWKKKKKWWKKKKKWWKKWWWWKK#WKKKKE;i;;i;i;i;i;;ii;;i;;;i;;;i;i
iiiiitiiiiLDEEEEKKKKKKKWWWKKKKKKWWW#########W#WKKWWWWW######WWWWWWWWWW#W#############tttjjjjjjjjjjjjjjttitfLGLLD##WWWKKKKWWWWW#WWWKKWKWWKKKK#KWKKKKKWWKKKKKWWKKWWKKKKWWKKKEKtiiiii;;i;;;i;i;i;i;i;iiiii;
iiiiiiiitiDDEEEEKKKKKKKKWWKWWKKWWKWW########W#WWWWWWW#W#W###WWW#WWWWW#WWW##W#########LLLLLLfffffffjffLLffffGGGfL##WWKKKKWWW#WWWWWWWWWWWWWKKK#WWKKKKKKKKKKKKKWWW#WKKWWWWWKKKKE;;;iii;;;iii;i;i;;;iii;;ii;
iiiiiiiiijDDEEEEEKEKKKKKKKKKWKWWWWKWW#######W#WWWWWWWWKWWWW#WWW#WWW#WW#WW##W#########DDDGDGGGLLffffffGGGLLfLGGff#WKKKKKWWWWWWWWWWWWWKWWWWWKK#WWWKKKKKKKKKKKKWWWWWWWWWWKWKKKKK;;iiii;i;iii;iii;iii;iiiiii
iiitiiiiiEDEEEKKWKKKKKKKWKKWWWWWWWWKW########WWWWWWWWWWWWWWWWWKWWWW########W#########WEKKKKEEDEDDttjfLDGGGLLLLffWWKKKKWWWWWWWWWWWWWWKWWWWWKW#WWWWKKKKKKKKKKKWWW#WWW##KWWWKKWK;iii;i;;ii;;iiiiiiiiii;iiii
iiittiiiiEEDEEKKWWKKKKKWWKKWKWKKKWWWWWW######WWWWWWWWWWWWWWWWWWWKWWW#####W#W##########KKKWKKEEWDjittfLGDDGLLLLffKWKKKKWWWW#WWWWWWWWWWWWWWWKK#WWWWWKKKKWKKKKKWWW###W#WKWWWKKKKi;;i;;i;;ii;iiiiiiii;iiiiii
iiitiiiiLEEEEEKKWWWWKWKWWWWWWWWKWWWWKWWW#######WWWWWWWWWWWWKWKKWWWKWWW#W##W###########WWW#WEftiitiitjLGDDGGLLLLfDWKKKKWWWWW##WWWWWWWWWWWWWWWWWWWWKKKWWWKKKKKK#W#WWW#WWWWWKKWKE;iiii;i;iii;i;iiiiiiii;;;i
iiiititiEKEEEKKKKW#WWWWWWWWWWKWKWKWWWWWWW####WWWWWWWW###WWWWKWWWWWWWWWWWW##############WGfjjjjtjtttjfLGDDGGLffLfLWKKWWWWWWWWWWWW#WWWWWWWWWWK#WWWWWWWKWWWWWWKWWWW#WWWWWWWWKWKKKi;i;iiiiiii;i;iiiiii;i;;ii
iiittiiiEKKEKKWWWKWWWWWWWWWWWWWWWWWWWWWWW#####WWWWWWWW#WWWWWKWWWWWWWWWWWWW##WW########WffffjjjffffffLLLLGGGLLLfffEKWWWWWWW#WW#WWWWWWWWWWWWWWW#WWWWWWWWWWWWWW#WW#WW#WWWWWWKEKEKj;iiiiiiiiiiiii;ii;;iiii;i
iiittiitKKWKKWWWWKWWWWWWWWWWWWWWWWWWWWWWWW####W#WWWWWWWWWWWWWKWKWWWWWWWWWW###W########EfLffjjjfLLLLLfLLLLGLLLLfffGWWWWWWWW#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#WW#WW#KWWWWWKEEEKL;iiiiiiiiiiiiiii;;iiit;ii
iiittiiDKWWKKKWW#WWWWWWWWWWWWWWWWWWWWWWWWW####WWWWWWW#WWWWWKWWKWWWWKWWWWWW#W#WW#######KDGGGLLLGGEDDGLffLLLLLLLffffWWWWWWWW####WW##WWWWWWWWWWWWWW#WWW#WWWW#W####WWWWWWWWWWKKKEKE;iiii;;iiiiiii;ii;iiii;;i
iiittiiKKWWWWKWWW##WWW##WWWWWWWWWWWWKWWWWWW#####W#WW##WWWWWWWWWWKWWWWWWWWWWWWWW##WW####WEKEDGDDDEEEEDLLffLLLffffffWW#W#WW#####WWWWWW#WWWWWWWWWW#WWWWWWWW#######WW#WWWWWWKEKKKKEt;iiii;i;iiiiiiiiii;;tiii
itittitKKWWWWWWWWW#WW######WWWWWWWKWWWWWWW#######WWWW#WWWWWWWWWWKWWWKWWWWWWWWWW##W######WWKKEDEEEEEEDGGfLLLffffLfjW###WWW#####WWWW#WWWWWWW#W##WW#WWWWWWW#######WW#WWWWWKKKKKKKEf;iiiiiiiiiiiiiiiiiiiti;;
iiittiLKWWWW#W######W###W#W##W###WWWWWWWWW####WWW#WW###WWWWKWWWWWWWKWWWWWWWWW#WW#WW##W##WWWW#KKKKKKEEDGLLLLLLLLfffD###W########WWW#WWW#WW#W##WWWWWW#W##W######WWWWWWWWKKKKKKKKED;iiiiiiiiii;;i;i;iiii;ii
tiiitiGKWW#WWWWKW####WW#####W###W#WWWWWWWWW######W######WWWWWWWWWWWWWWWWWWWWWW#WW#WW##W###WW#KKKKEKKEDDGLLLLLLLffffW##W###########WW#######W#WWW#WW#W##########W#W#WKWKKWKWWKKKE;iiiiii;ii;;;;;i;;iiii;;
iiiiiiDWWWWWWWWWWKKKW#############WWWWWWW#W######W#####WWWW#W#WWWWWWWWWWWWWWWWW#W#WW##W######EKKKEEKDEDGLLLLLfLLfffGW##WWWWWWWWWWWWWWWWWWWW####W#################WWWWKWKWWWWKKKK;;iii;;iii;i;i;iiiiii;ii
tiiiiiEWWW#WWWWWWWKKWWWW#########W#WWWWWWW#############WWWW#WWW#WWWWWWWWWWWWWW##WWWW#########EEEEKEEEDDDGGLLLLLLffffDWWWWWWWWWWWWWKWWKWWWWWWWW#WWWWWW#########W#WKKWWKWWKWWWKKKW;ii;iiii;i;i;;iiiiiiiiii
iiiiiiKKKWKKKWW####WKKKWWW###########WW#WWWW############W##W#WW#WWWWWWWWWWWW#WW#W############W##KEEEDEDDGGLGLLLLffffjWWWWWWWWWWWWWKKKWKWWWWWWWWWWWWWWWWW######W#WKWWWWWWWWWWKWWE;iiiiiiiii;i;iiiiiiiiiii
titiiiKKWEDEKKWWWWWWWWKKW#############W#W#W##################WW#WWWWWWWWWWW##W#WWW##############EEEDDDDDGGGLLLLLLffjjjWWWWWKWWWWWWWKWWWKWWWWWKWWWWWWWWWW#WW#WWWWWWWWWWWWWWWWWWKK;;i;i;iii;;iiiiiiiiiiiii
iiiiiiDKDEDDKEKEKKKKKKKKKKW############W###W##WWW#############W####WW#WWWWW###W#WW##############KEEDDDDGGGGGGLfffffjjjLWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#W#WWW###WW#WW#WWWW#WKWW;;;;iiiiiiiiii;ii;iiiiii
tiiiiiGDDDDEEKEEEKEEEKKWKKKWW#################WW#W###W#######WW#####W##WWWWW##W#################WEEEDGDDDDGGGGLLfLffjjjWWWWWWWWWWWWKWWWWWWWWWKWWWWWWWWW#WW#WWW##W#W###W#W##WWKKK;iiiii;iiiiiiiii;ii;iiii
itititDDDDEEDEKKKKKKKKKKKWKKKKWW###############WWWWW########WW########W##W#W##W##################EEEEEDDDDDDGGLfjffffjjfEWWWWWWWWWWKWWWWWWWWWWWWWWWWWW#####WWW#WWW###WWW#WKKKWEK;i;ii;iiii;iiiiiii;iiiii
itiitiDDDDEEKKEKKKKKKKWWWWKWKWKWW###############WWWW#WWWWW##############WWW######################WKKEEDEEDDDDGLffjjffjjjj#WWWWWWWWWWWW#WWWWWWWWWWWWW#####WWWWWW#########KKKKKKKKti;iiiiiiiiii;ii;iiiiii;
tiiiitEEEEEEKKKKKKKKKWWWWWWWWWKWW###############WWWWWWWWWWWW#W###W#################W##############WKKEKEEEGDDGLLffjjjjjjjEWKKWWWWWWWWW#WWWWWWWWWWWWW####W#WWW#######W##WWWKEKKKWfiiiiii;iiiiiiiii;i;iii;
ttttiDDEEEKKKKEKKKKKWWWWWWWW#W#WWKWWW##########WWWW#WKWWKWWWWWWWWWWW##################W############WKKKKKEEDEDLfffjjjjjjjLWKKKWWWWWWW#WWWWWWWWWWW##W###W#WWWW######W##WWWKKKKWKKGiiiii;i;iiiiiii;iii;iii
titiiEEKKKKKKKEEKKKWWWWWWWWW#####WWWWW#########WWW#WWWWWKWWWWKWKWWWWWWWWWW#########################WKWKWKKEEDGGLfffjjttjjDWKEWWWWWWKWWWWWWWWWW#WWW######WWWWW####WW##WWWKKWKWWKKD;iii;i;iii;;i;ii;iiii;i
tiiiGEKKWWWWWWKKKKWWWWW####WW#####WWWWWW#######W#W#WKWWWWWWWWKWKWWWWWWWKKKWW########################WKWWKKKEDDGGLLfjjtttjKKEKKWW##WKKKKKWWWWWW#W########WWW#####WW#WKWWWWWKKKKWWK;ii;i;ii;;iiiiiiiiiiiii
*/
